import { Router, Request, Response } from 'express';
import { Resend } from 'resend';

export const emailRouter = Router();

interface EmailRequestBody {
  email: string;
  letterContent: string;
  userData?: {
    simulation?: {
      currentBiologicalAge: number;
      chronologicalAge: number;
      topHabitChange: { habit: string; potentialYearsGained: number };
    };
  };
}

function buildEmailHtml(letterContent: string, chronoAge: number): string {
  const futureAge = chronoAge + 30;
  const paragraphs = letterContent
    .split('\n')
    .map((line) => (line.trim() ? `<p style="margin:0 0 12px;line-height:1.7">${line}</p>` : '<br/>'))
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="background:#0f172a;margin:0;padding:32px 16px;font-family:Georgia,serif">
  <div style="max-width:600px;margin:0 auto">
    <div style="text-align:center;margin-bottom:32px">
      <h1 style="color:#fff;font-size:32px;margin:0">Echo<span style="color:#a855f7">60</span></h1>
      <p style="color:#94a3b8;margin:8px 0 0;font-family:sans-serif;font-size:14px">A message from your past and future selves</p>
    </div>
    
    <div style="background:linear-gradient(135deg,#fdf6e3,#f5e6c8);border-radius:16px;padding:32px;margin-bottom:24px;box-shadow:0 20px 60px rgba(0,0,0,0.5)">
      <div style="color:#7c5c3e;font-size:11px;font-family:sans-serif;text-transform:uppercase;letter-spacing:2px;margin-bottom:16px">From Your Current Self — Age ${chronoAge}</div>
      <div style="color:#3d2b1f;font-size:15px">
        ${paragraphs}
      </div>
    </div>
    
    <div style="background:linear-gradient(135deg,#e8f5e9,#c8e6c9);border-radius:16px;padding:32px;margin-bottom:24px;box-shadow:0 20px 60px rgba(0,0,0,0.5)">
      <div style="color:#2e7d32;font-size:11px;font-family:sans-serif;text-transform:uppercase;letter-spacing:2px;margin-bottom:16px">From Your Future Self — Age ${futureAge}</div>
      <div style="color:#1b5e20;font-size:15px">
        <p style="margin:0 0 12px;line-height:1.7">The future you is rooting for you. Every choice you make today creates the life you'll live in 30 years.</p>
        <p style="margin:0 0 12px;line-height:1.7">Start with the one change that matters most. Then another. Then another.</p>
        <p style="margin:0;line-height:1.7;font-style:italic">With love across time,<br/>Your ${futureAge}-year-old self</p>
      </div>
    </div>
    
    <div style="text-align:center;color:#475569;font-family:sans-serif;font-size:12px">
      <p>Generated by Echo60 — Your health, your future, your choice.</p>
    </div>
  </div>
</body>
</html>`;
}

emailRouter.post('/', async (req: Request, res: Response) => {
  const { email, letterContent, userData } = req.body as EmailRequestBody;

  if (!email || !email.includes('@')) {
    res.status(400).json({ error: 'Invalid email address' });
    return;
  }

  if (!process.env.RESEND_API_KEY) {
    res.status(503).json({ error: 'Email service not configured' });
    return;
  }

  try {
    const resend = new Resend(process.env.RESEND_API_KEY);
    const chronoAge = userData?.simulation?.chronologicalAge ?? 30;

    const { error } = await resend.emails.send({
      from: 'Echo60 <noreply@echo60.app>',
      to: [email],
      subject: `A letter from your ${chronoAge}-year-old self`,
      html: buildEmailHtml(letterContent, chronoAge),
    });

    if (error) {
      console.error('Resend error:', error);
      res.status(500).json({ error: 'Failed to send email' });
      return;
    }

    res.json({ success: true });
  } catch (err) {
    console.error('Email error:', err);
    res.status(500).json({ error: 'Failed to send email' });
  }
});
